# flake8: noqa

# This file is autogenerated by /metadata-ingestion/scripts/avro_codegen.py
# Do not modify manually!

# fmt: off
from .....schema_classes import DataHubActorFilterClass
from .....schema_classes import DataHubPolicyInfoClass
from .....schema_classes import DataHubResourceFilterClass
from .....schema_classes import PolicyMatchConditionClass
from .....schema_classes import PolicyMatchCriterionClass
from .....schema_classes import PolicyMatchFilterClass


DataHubActorFilter = DataHubActorFilterClass
DataHubPolicyInfo = DataHubPolicyInfoClass
DataHubResourceFilter = DataHubResourceFilterClass
PolicyMatchCondition = PolicyMatchConditionClass
PolicyMatchCriterion = PolicyMatchCriterionClass
PolicyMatchFilter = PolicyMatchFilterClass

# fmt: on
